# Use the official Python base image
FROM python:3-slim

# Set the working directory in the container
WORKDIR /app

# Copy the Python dependencies file
COPY requirements.txt .

RUN apt-get update && apt-get install -y gcc && apt-get clean

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the Python script as the default command
CMD ["./run.sh", "analog"]
